name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Install latest nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - name: Build for window
        if: matrix.os == 'windows-latest'
        run: cargo build --verbose -Z unstable-options --out-dir artifacts --no-default-features --features "vulkan"
      - name: Build for macos
        if: matrix.os == 'macos-latest'
        run: cargo build --verbose -Z unstable-options --out-dir artifacts --no-default-features --features "metal"
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          path: ${{ github.workspace }}/artifacts
          name: ${{ matrix.os }}-${{ github.run_number }}
      - name: Upload config
        uses: actions/upload-artifact@v1
        with:
          path: ${{ github.workspace }}/config
          name: ${{ matrix.os }}-${{ github.run_number }}
      - name: Upload assets
        uses: actions/upload-artifact@v1
        with:
          path: ${{ github.workspace }}/assets
          name: ${{ matrix.os }}-${{ github.run_number }}
